# Text Classification Assessment
This assessment is very much like the Text Classification Project we just completed, and the dataset is very similar.

The **moviereviews2.tsv** dataset contains the text of 6000 movie reviews. 3000 are positive, 3000 are negative, and the text has been preprocessed as a tab-delimited file. As before, labels are given as `pos` and `neg`.

We've included 20 reviews that contain either `NaN` data, or have strings made up of whitespace.

For more information on this dataset visit http://ai.stanford.edu/~amaas/data/sentiment/

### Task #1: Perform imports and load the dataset into a pandas DataFrame ,

---
Store **in variable df_npm**

For this exercise you can load the dataset from `'../TextFiles/moviereviews2.tsv'`.

In [1]:
import pandas as pd
import numpy as np
df_714220016 = pd.read_csv('moviereviews.tsv', sep='\t')
df_714220016.head()






,label,review
0,neg,how do films like mouse hunt get into theatres...
1,neg,some talented actresses are blessed with a dem...
2,pos,this has been an extraordinary year for austra...
3,pos,according to hollywood movies made in last few...
4,neg,my first press screening of 1998 and already i...


### Task #2: Check for missing values:

In [2]:
# Check for NaN values:
missing_values = df_714220016.isnull().sum()
print("jumlah missing values")
print(missing_values)

jumlah missing values
label      0
review    35
dtype: int64


In [3]:
# Check for whitespace strings (it's OK if there aren't any!):
print("jumlah whitespace strings")
whitespace_strings_count = {}
for column in df_714220016.select_dtypes(include=[object]).columns:
    is_whitespace_or_empty_after_strip = (df_714220016[column].astype(str).str.strip() == '') & (~df_714220016[column].isnull())
    count = is_whitespace_or_empty_after_strip.sum()
    if count > 0:
        whitespace_strings_count[column] = count

if whitespace_strings_count:
    print("Jumlah 'whitespace strings' (string yang hanya berisi spasi/kosong setelah strip) per kolom:")
    for col, count in whitespace_strings_count.items():
        print(f"- Kolom '{col}': {count} entri")
else:
    print("Tidak ditemukan 'whitespace strings' di kolom bertipe string.")

jumlah whitespace strings
Jumlah 'whitespace strings' (string yang hanya berisi spasi/kosong setelah strip) per kolom:
- Kolom 'review': 27 entri


### Task #3: Remove NaN values:

In [4]:
# hapus NaN
print("shape sebelum menghapus NaN", df_714220016.shape)
initial_rows = df_714220016.shape[0]

print("\nMemulai proses menghapus baris yang mengandung NaN...")
df_714220016_after_nan_removal = df_714220016.dropna(how='any')
print("Shape DataFrame setelah penghapusan NaN:", df_714220016_after_nan_removal.shape)
rows_removed_nan = initial_rows - df_714220016_after_nan_removal.shape[0]
print(f"Jumlah baris yang dihapus karena NaN: {rows_removed_nan}")

# hapus whitespace strings
print("\nMemulai proses menghapus baris yang mengandung hanya whitespace strings...")
string_columns = df_714220016_after_nan_removal.select_dtypes(include='object').columns

whitespace_mask = pd.Series([False] * len(df_714220016_after_nan_removal), index=df_714220016_after_nan_removal.index)
for col in string_columns:
    col_is_whitespace = df_714220016_after_nan_removal[col].astype(str).str.strip() == ''
    whitespace_mask = whitespace_mask | col_is_whitespace # Combine masks with OR operation

df_714220016_clean_final = df_714220016_after_nan_removal[~whitespace_mask]
print("Shape DataFrame setelah penghapusan whitespace strings:", df_714220016_clean_final.shape)
rows_removed_whitespace = df_714220016_after_nan_removal.shape[0] - df_714220016_clean_final.shape[0]
print(f"Jumlah baris yang dihapus karena whitespace strings: {rows_removed_whitespace}")

total_rows_removed = rows_removed_nan + rows_removed_whitespace
print(f"Total jumlah baris yang dihapus: {total_rows_removed}")

print("\n5 baris pertama DataFrame setelah pembersihan:")
print(df_714220016_clean_final.head())

print("\nJumlah missing values setelah pembersihan:")
print(df_714220016_clean_final.isnull().sum())

print("\nPengecekan ulang whitespace strings (seharusnya tidak ada):")
whitespace_check_final = {}
for column in df_714220016_clean_final.select_dtypes(include=[object]).columns:
    is_whitespace_or_empty_after_strip = (df_714220016_clean_final[column].astype(str).str.strip() == '') & (~df_714220016_clean_final[column].isnull())
    count = is_whitespace_or_empty_after_strip.sum()
    if count > 0:
        whitespace_check_final[column] = count
if whitespace_check_final:
    print("Masih ada 'whitespace strings' di kolom berikut:")
    for col, count in whitespace_check_final.items():
        print(f"- Kolom '{col}': {count} entri")
else:
    print("Tidak ditemukan 'whitespace strings' di DataFrame setelah pembersihan.")



shape sebelum menghapus NaN (2000, 2)

Memulai proses menghapus baris yang mengandung NaN...
Shape DataFrame setelah penghapusan NaN: (1965, 2)
Jumlah baris yang dihapus karena NaN: 35

Memulai proses menghapus baris yang mengandung hanya whitespace strings...
Shape DataFrame setelah penghapusan whitespace strings: (1938, 2)
Jumlah baris yang dihapus karena whitespace strings: 27
Total jumlah baris yang dihapus: 62

5 baris pertama DataFrame setelah pembersihan:
  label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

Jumlah missing values setelah pembersihan:
label     0
review    0
dtype: int64

Pengecekan ulang whitespace strings (seharusnya tidak ada):
Tidak ditemukan 'whitespace strings' 

### Task #4: Take a quick look at the `label` column:

In [5]:
labels_count = df_714220016_clean_final['label'].value_counts()
print("\nJumlah label unik dalam kolom 'label':")

labels_dtypes = df_714220016_clean_final['label'].dtype
print(f"Jumlah label unik: {labels_count.size}")

print("Analisis Kolom 'label':\n")
print("Jumlah kemunculan setiap nilai unik di kolom 'label':")
print(labels_count)
print("\n")
print(f"Tipe data kolom 'label': {labels_dtypes}")




Jumlah label unik dalam kolom 'label':
Jumlah label unik: 2
Analisis Kolom 'label':

Jumlah kemunculan setiap nilai unik di kolom 'label':
label
neg    969
pos    969
Name: count, dtype: int64


Tipe data kolom 'label': object


### Task #5: Split the data into train & test sets:
You may use whatever settings you like. To compare your results to the solution notebook, use `test_size=0.33, random_state=42`.


---
**rule**:
X_npm, y_npm.


In [6]:
from sklearn.model_selection import train_test_split

#split data
print("\nMemisahkan data menjadi fitur (x) dan label (y)...")
x_714220016 = df_714220016_clean_final['review']
y_714220016 = df_714220016_clean_final['label']

x_714220016_train, x_714220016_test, y_714220016_train, y_714220016_test = train_test_split(x_714220016, y_714220016, test_size=0.33, random_state=42)


print("Data berhasil dibagi.")
print(f"Shape X_train: {x_714220016_train.shape}")
print(f"Shape X_test: {x_714220016_test.shape}")
print(f"Shape y_train: {y_714220016_train.shape}")
print(f"Shape y_test: {y_714220016_test.shape}")


Memisahkan data menjadi fitur (x) dan label (y)...
Data berhasil dibagi.
Shape X_train: (1298,)
Shape X_test: (640,)
Shape y_train: (1298,)
Shape y_test: (640,)


### Task #6: Build a pipeline to vectorize the date, then train and fit a model
You may use whatever model you like. To compare your results to the solution notebook, use `LinearSVC`.
---
**rule**:
**npm_model**

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score

# Membuat pipeline untuk TF-IDF dan model SVM
pipeline_714220016 = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('svm', LinearSVC())
])

# Melatih model
pipeline_714220016.fit(x_714220016_train, y_714220016_train)


Pipeline(steps=[('tfidf', TfidfVectorizer()), ('svm', LinearSVC())])

### Task #7: Run predictions and analyze the results

---
**rule: npm_pred**


In [8]:
# Form a prediction set
print("\nMembuat prediksi pada data uji...")
predictions_714220016 = pipeline_714220016.predict(x_714220016_test)
print("Prediksi berhasil dibuat.")


Membuat prediksi pada data uji...
Prediksi berhasil dibuat.


In [9]:
# Report the confusion matrix
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score # Import confusion_matrix
print("\nConfusion Matrix:")
cm = confusion_matrix(y_714220016_test, predictions_714220016)
print(cm)


Confusion Matrix:
[[259  49]
 [ 49 283]]


In [10]:
# Print a classification report
print("\nClassification Report:")
print(classification_report(y_714220016_test, predictions_714220016))


Classification Report:
              precision    recall  f1-score   support

         neg       0.84      0.84      0.84       308
         pos       0.85      0.85      0.85       332

    accuracy                           0.85       640
   macro avg       0.85      0.85      0.85       640
weighted avg       0.85      0.85      0.85       640



In [11]:
# Print the overall accuracy
print(f"Akurasi Model: {accuracy_score(y_714220016_test, predictions_714220016):.4f}")

Akurasi Model: 0.8469


## Task #8 : Apply Stopword

In [12]:
#Membuat Pipeline dengan Stopword Removal di TfidfVectorizer
pipeline_714220016_stopwords = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('svm', LinearSVC())
])

# Melatih model dengan stopword removal
pipeline_714220016_stopwords.fit(x_714220016_train, y_714220016_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(stop_words='english')),
                ('svm', LinearSVC())])

In [13]:
#prediksi dengan model yang menggunakan stopword removal
predictions_714220016_stopwords = pipeline_714220016_stopwords.predict(x_714220016_test)
# Report the confusion matrix untuk model dengan stopword removal
print("\nConfusion Matrix dengan Stopword Removal:")
cm_stopwords = confusion_matrix(y_714220016_test, predictions_714220016_stopwords)
print(cm_stopwords)
# Print a classification report untuk model dengan stopword removal
print("\nClassification Report dengan Stopword Removal:")
print(classification_report(y_714220016_test, predictions_714220016_stopwords))
# Print the overall accuracy untuk model dengan stopword removal
print(f"Akurasi Model dengan Stopword Removal: {accuracy_score(y_714220016_test, predictions_714220016_stopwords):.4f}")


Confusion Matrix dengan Stopword Removal:
[[252  56]
 [ 52 280]]

Classification Report dengan Stopword Removal:
              precision    recall  f1-score   support

         neg       0.83      0.82      0.82       308
         pos       0.83      0.84      0.84       332

    accuracy                           0.83       640
   macro avg       0.83      0.83      0.83       640
weighted avg       0.83      0.83      0.83       640

Akurasi Model dengan Stopword Removal: 0.8313


## Task #9 : Compare to other Algortihm

In [14]:
#Knn Classifier
from sklearn.neighbors import KNeighborsClassifier

# Membuat pipeline untuk TF-IDF dan model KNN
pipeline_714220016_knn = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('knn', KNeighborsClassifier(n_neighbors=5))
])
# Melatih model KNN
pipeline_714220016_knn.fit(x_714220016_train, y_714220016_train)

# Form a prediction set dengan model KNN
predictions_714220016_knn = pipeline_714220016_knn.predict(x_714220016_test)

# Report the confusion matrix untuk model KNN
print("\nConfusion Matrix untuk KNN:")
cm_knn = confusion_matrix(y_714220016_test, predictions_714220016_knn)
print(cm_knn)

# Print a classification report untuk model KNN
print("\nClassification Report untuk KNN:")
print(classification_report(y_714220016_test, predictions_714220016_knn))

# Print the overall accuracy untuk model KNN
print(f"Akurasi Model KNN: {accuracy_score(y_714220016_test, predictions_714220016_knn):.4f}")


Confusion Matrix untuk KNN:
[[180 128]
 [ 89 243]]

Classification Report untuk KNN:
              precision    recall  f1-score   support

         neg       0.67      0.58      0.62       308
         pos       0.65      0.73      0.69       332

    accuracy                           0.66       640
   macro avg       0.66      0.66      0.66       640
weighted avg       0.66      0.66      0.66       640

Akurasi Model KNN: 0.6609


In [15]:
#Naive Bayes
from sklearn.naive_bayes import MultinomialNB
# Membuat pipeline untuk TF-IDF dan model Naive Bayes
pipeline_714220016_nb = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('nb', MultinomialNB())
])

# Melatih model Naive Bayes
pipeline_714220016_nb.fit(x_714220016_train, y_714220016_train)

# Form a prediction set dengan model Naive Bayes
predictions_714220016_nb = pipeline_714220016_nb.predict(x_714220016_test)

# Report the confusion matrix untuk model Naive Bayes
print("\nConfusion Matrix untuk Naive Bayes:")
cm_nb = confusion_matrix(y_714220016_test, predictions_714220016_nb)
print(cm_nb)

# Print a classification report untuk model Naive Bayes
print("\nClassification Report untuk Naive Bayes:")
print(classification_report(y_714220016_test, predictions_714220016_nb))

# Print the overall accuracy untuk model Naive Bayes
print(f"Akurasi Model Naive Bayes: {accuracy_score(y_714220016_test, predictions_714220016_nb):.4f}")


Confusion Matrix untuk Naive Bayes:
[[274  34]
 [ 94 238]]

Classification Report untuk Naive Bayes:
              precision    recall  f1-score   support

         neg       0.74      0.89      0.81       308
         pos       0.88      0.72      0.79       332

    accuracy                           0.80       640
   macro avg       0.81      0.80      0.80       640
weighted avg       0.81      0.80      0.80       640

Akurasi Model Naive Bayes: 0.8000


In [16]:
#logistic regression
from sklearn.linear_model import LogisticRegression

# Membuat pipeline untuk TF-IDF dan model Logistic Regression
pipeline_714220016_lr = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('lr', LogisticRegression(max_iter=1000))
])

# Melatih model Logistic Regression
pipeline_714220016_lr.fit(x_714220016_train, y_714220016_train)

# Form a prediction set dengan model Logistic Regression
predictions_714220016_lr = pipeline_714220016_lr.predict(x_714220016_test)

# Report the confusion matrix untuk model Logistic Regression
print("\nConfusion Matrix untuk Logistic Regression:")
cm_lr = confusion_matrix(y_714220016_test, predictions_714220016_lr)
print(cm_lr)

# Print a classification report untuk model Logistic Regression
print("\nClassification Report untuk Logistic Regression:")
print(classification_report(y_714220016_test, predictions_714220016_lr))

# Print the overall accuracy untuk model Logistic Regression
print(f"Akurasi Model Logistic Regression: {accuracy_score(y_714220016_test, predictions_714220016_lr):.4f}")


Confusion Matrix untuk Logistic Regression:
[[246  62]
 [ 62 270]]

Classification Report untuk Logistic Regression:
              precision    recall  f1-score   support

         neg       0.80      0.80      0.80       308
         pos       0.81      0.81      0.81       332

    accuracy                           0.81       640
   macro avg       0.81      0.81      0.81       640
weighted avg       0.81      0.81      0.81       640

Akurasi Model Logistic Regression: 0.8063


## Task #10 : Check Accuration

In [18]:
print(f"Akurasi Model Linear SVC (dengan stop word): {accuracy_score(y_714220016_test, predictions_714220016_stopwords):.4f}")
print(f"Akurasi Model KNN (dengan stop word): {accuracy_score(y_714220016_test, predictions_714220016_knn):.4f}")
print(f"Akurasi Model Logistic Regression (dengan stop word): {accuracy_score(y_714220016_test, predictions_714220016_lr):.4f}")
print(f"Akurasi Model Naive Bayes (dengan stop word): {accuracy_score(y_714220016_test, predictions_714220016_nb):.4f}")

Akurasi Model Linear SVC (dengan stop word): 0.8313
Akurasi Model KNN (dengan stop word): 0.6609
Akurasi Model Logistic Regression (dengan stop word): 0.8063
Akurasi Model Naive Bayes (dengan stop word): 0.8000
